[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "normalizer"
version = "0.1.0"
requires-python = "~=3.11.0"
dependencies = [
    "pyyaml>=6.0.3",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.hatch.build.targets.wheel]
packages = ["src/normalizer"]
